#!/usr/bin/env zsh

deps yt-dlp fzf mpv curl chafa awk || exit 1

thumb_dir="/tmp/ytsearch_thumbs"
thumb_quality="mqdefault"
thumb_rows=10
result_count=20

render_thumb() {
  local id="$1" thumb
  mkdir -p "$thumb_dir"
  thumb="$thumb_dir/$id.jpg"
  [ -s "$thumb" ] || curl -sf "https://i.ytimg.com/vi/$id/$thumb_quality.jpg" -o "$thumb"
  chafa --size=999x${thumb_rows} "$thumb" 2>/dev/null
}

[[ "$1" == "--render-thumb" ]] && { render_thumb "$2"; exit 0; }

audio_only=1
loop=0
[[ "${0##*/}" == "ytvsearch" ]] && audio_only=0

while [[ "$1" == -* ]]; do
  case "$1" in
    -v|--video) audio_only=0 ;;
    -l|--loop) loop=1 ;;
    *) echo "usage: ytsearch [-v|--video] [-l|--loop] <query>"; exit 1 ;;
  esac
  shift
done
query="$*"
[ -n "$query" ] || { echo "usage: ytsearch [-v|--video] [-l|--loop] <query>"; exit 1; }

self="${0:A}"
fields=$'%(id)s\t%(title)s\t%(channel)s'

results=$(yt-dlp "ytsearch${result_count}:$query" --flat-playlist --no-warnings --print "$fields" 2>/dev/null | awk -F'\t' -v OFS='\t' '{print $1, $2, $3, $3" - "$2}')
selected=$(fzf --delimiter '\t' --with-nth=4 --preview "'$self' --render-thumb \$(cut -f1 <<< {})" --preview-window=up:${thumb_rows} --layout=reverse <<< "$results")

[ -n "$selected" ] || exit 0
id=$(cut -f1 <<< "$selected")
title=$(cut -f2 <<< "$selected")
channel=$(cut -f3 <<< "$selected")

render_thumb "$id"
echo "$channel - $title"
echo

mpv_opts=(--msg-level=all=error,ffmpeg=fatal "--force-media-title=$title" --term-status-msg='${media-title}  ${time-pos} / ${duration}')
(( loop )) && mpv_opts+=(--loop-file=inf)
(( audio_only )) && mpv_opts+=(--no-video) || mpv_opts+=(--hwdec=auto)
mpv "${mpv_opts[@]}" "https://youtube.com/watch?v=$id"
